# Generated by Django 5.2.1 on 2025-05-25 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("login_url", models.URLField()),
                ("description", models.TextField()),
                ("logo_url", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai_chat", "AI Chat"),
                            ("ai_image", "AI Image"),
                            ("seo", "SEO Tools"),
                            ("analytics", "Analytics"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="service_app_name_e802ab_idx"),
                    models.Index(
                        fields=["category"], name="service_app_categor_2e3796_idx"
                    ),
                ],
            },
        ),
    ]
