# Generated by Django 5.2.1 on 2025-05-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('ai_chat', 'AI Chat'), ('ai_image', 'AI Image'), ('seo', 'SEO Tools'), ('analytics', 'Analytics'), ('writing', 'Writing Tools'), ('social_media', 'Social Media'), ('design', 'Design Tools'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
