# Generated by Django 5.2.1 on 2025-05-28 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_management_app', '0001_initial'),
        ('service_app', '0003_alter_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('extracted_cookies_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cookie',
            options={'ordering': ['-extracted_at']},
        ),
        migrations.AlterModelOptions(
            name='cookieinjectionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='loginservice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userservice',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.RemoveField(
            model_name='userservice',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cookie',
            name='validation_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookieinjectionlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginservice',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('pending_validation', 'Pending Validation')], default='pending_validation', max_length=20),
        ),
        migrations.AlterField(
            model_name='cookieinjectionlog',
            name='injection_status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('expired', 'Cookie Expired'), ('invalid', 'Invalid Cookie'), ('access_denied', 'Access Denied')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='cookie',
            index=models.Index(fields=['status', 'expires_at'], name='cookie_mana_status_37743e_idx'),
        ),
        migrations.AddIndex(
            model_name='cookie',
            index=models.Index(fields=['user_service', 'status'], name='cookie_mana_user_se_dd6682_idx'),
        ),
        migrations.AddIndex(
            model_name='cookie',
            index=models.Index(fields=['session_id'], name='cookie_mana_session_725277_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieinjectionlog',
            index=models.Index(fields=['user', 'timestamp'], name='cookie_mana_user_id_d907f5_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieinjectionlog',
            index=models.Index(fields=['injection_status', 'timestamp'], name='cookie_mana_injecti_f17650_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieinjectionlog',
            index=models.Index(fields=['cookie', 'injection_status'], name='cookie_mana_cookie__e7f0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='loginservice',
            index=models.Index(fields=['service', 'is_active'], name='cookie_mana_service_8957b0_idx'),
        ),
        migrations.AddIndex(
            model_name='loginservice',
            index=models.Index(fields=['is_active', 'current_users'], name='cookie_mana_is_acti_0698a7_idx'),
        ),
        migrations.AddIndex(
            model_name='userservice',
            index=models.Index(fields=['user', 'status'], name='cookie_mana_user_id_0ab6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='userservice',
            index=models.Index(fields=['service', 'status'], name='cookie_mana_service_47434a_idx'),
        ),
        migrations.AddIndex(
            model_name='userservice',
            index=models.Index(fields=['status', 'assigned_at'], name='cookie_mana_status_6b6ed9_idx'),
        ),
        migrations.AddField(
            model_name='cookieextractionjob',
            name='login_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='cookie_management_app.loginservice'),
        ),
        migrations.AddIndex(
            model_name='cookieextractionjob',
            index=models.Index(fields=['status', 'created_at'], name='cookie_mana_status_2f2b25_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieextractionjob',
            index=models.Index(fields=['login_service', 'status'], name='cookie_mana_login_s_d9f97f_idx'),
        ),
    ]
