# Generated by Django 5.2.1 on 2025-05-25 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("crypto", "Cryptocurrency"),
                        ],
                        max_length=30,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("payment_metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
