# Generated by Django 5.2.1 on 2025-05-28 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_initial'),
        ('subscription_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'payment_status'], name='payment_app_user_id_0ee31f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status', 'payment_date'], name='payment_app_payment_d21e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'payment_status'], name='payment_app_payment_e18de5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payment_app_transac_d428ab_idx'),
        ),
    ]
